spring:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
  profiles:
    active: dev
app:
  jwtSecret: hu\St}{k]:}:R2*V9ax7 #${JWT_SECRET}
  jwtExpirationMs: 600000000
