spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
  profiles:
    active: prod
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 600000000
