spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionappdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
app:
  jwtSecret: hu\St}{k]:}:R2*V9ax7
  jwtExpirationMs: 604800000
server:
  port: 8080
