spring:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
  profiles:
    active: dev
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 300000
