spring:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
  profiles:
    active: dev
  sendgrid:
    api-key: ${MAIL_API_KEY}
    sender: ${SENDER}
    reset-url: ${RESET_URL}
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 600000000
